### ISSUE TITLE
Could you provide a demo that can work with one-click

### ISSUE THREAD

**Issue by yichuan1998** [facebookresearch/banmo#62] opened 2023-08-22 06:59 UTC
I ran "bash scripts/render_nvs.sh 0 $seqname tmp/cat-pikachiu.pth 5 0" and got a lot errors:
![image](https://github.com/facebookresearch/banmo/assets/91551667/aa7aa843-e536-4571-8d22-de96dad18d41)

**Comment by gengshan-y** [comment] 2023-08-23 04:36
Possibly a duplicate of this https://github.com/facebookresearch/banmo/issues/55 and [this](https://github.com/facebookresearch/banmo#common-install-issues).

I don't plan to further develop this repo. Please feel free to check a more recent codebase if that suits your needs better: https://lab4d-org.github.io/lab4d/

**Closed by gengshan-y** 2023-08-23 04:36 UTC
